# Generated by Django 3.0.4 on 2020-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pro',
            field=models.CharField(blank=True, default='pro.jpeg', max_length=200),
        ),
    ]
