# Generated by Django 3.0.4 on 2020-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200426_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pro',
            field=models.URLField(blank=True, default='pro.jpeg'),
        ),
    ]
